name: Artifact-Download-Reusable-workflow
on:
  workflow_call:
jobs:
  
  Artifact-Download:
    runs-on: windows-latest
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: drop-${{ github.sha }}
    
