name: Maven-Build-Reusable-workflow
on:
  workflow_call:
    inputs:
      GLOBAL_MY_MAPPED_ENV_VAR:
        required: true
        type: string
      package:
        required: true
        type: string
    secrets:
      ADOVARIABLE:
        required: true
jobs:
  Maven-Build:
    runs-on: ubuntu-latest    
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - run: |-
        echo "Using an input-macro works for secrets var : ${{ secrets.ADOVARIABLE }}"
        echo "Using the env var directly does not work : ${{ inputs.GLOBAL_MY_MAPPED_ENV_VAR }}"
      shell: bash
    - name: Setup Java 8
      uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: '8'
    - name: Run maven
      run: mvn --file ${{ inputs.package }} package
      env:
        MAVEN_OPTS: "-Xmx3072m"  
